// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../internal/shared/repositories/payment/payment_repository.go
//
// Generated by this command:
//
//	mockgen -source=../../../../internal/shared/repositories/payment/payment_repository.go -destination=mock_payment_repo_test.go -package=payment
//

// Package payment is a generated GoMock package.
package payment

import (
	models "commerce/internal/shared/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepositoryI is a mock of PaymentRepositoryI interface.
type MockPaymentRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryIMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryIMockRecorder is the mock recorder for MockPaymentRepositoryI.
type MockPaymentRepositoryIMockRecorder struct {
	mock *MockPaymentRepositoryI
}

// NewMockPaymentRepositoryI creates a new mock instance.
func NewMockPaymentRepositoryI(ctrl *gomock.Controller) *MockPaymentRepositoryI {
	mock := &MockPaymentRepositoryI{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepositoryI) EXPECT() *MockPaymentRepositoryIMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPaymentRepositoryI) Delete(id uint, hard bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, hard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentRepositoryIMockRecorder) Delete(id, hard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentRepositoryI)(nil).Delete), id, hard)
}

// GetAll mocks base method.
func (m *MockPaymentRepositoryI) GetAll() ([]*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPaymentRepositoryIMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPaymentRepositoryI)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockPaymentRepositoryI) GetById(id uint) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPaymentRepositoryIMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPaymentRepositoryI)(nil).GetById), id)
}

// GetByOrder mocks base method.
func (m *MockPaymentRepositoryI) GetByOrder(orderId uint) ([]*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrder", orderId)
	ret0, _ := ret[0].([]*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrder indicates an expected call of GetByOrder.
func (mr *MockPaymentRepositoryIMockRecorder) GetByOrder(orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrder", reflect.TypeOf((*MockPaymentRepositoryI)(nil).GetByOrder), orderId)
}

// Save mocks base method.
func (m *MockPaymentRepositoryI) Save(payment *models.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPaymentRepositoryIMockRecorder) Save(payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPaymentRepositoryI)(nil).Save), payment)
}

// UpdateStatus mocks base method.
func (m *MockPaymentRepositoryI) UpdateStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPaymentRepositoryIMockRecorder) UpdateStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPaymentRepositoryI)(nil).UpdateStatus), id, status)
}
