// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../internal/shared/repositories/order/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=../../../../internal/shared/repositories/order/order_repository.go -destination=mock_order_repo_test.go -package=order
//

// Package order is a generated GoMock package.
package order

import (
	models "commerce/internal/shared/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepositoryI is a mock of OrderRepositoryI interface.
type MockOrderRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryIMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryIMockRecorder is the mock recorder for MockOrderRepositoryI.
type MockOrderRepositoryIMockRecorder struct {
	mock *MockOrderRepositoryI
}

// NewMockOrderRepositoryI creates a new mock instance.
func NewMockOrderRepositoryI(ctrl *gomock.Controller) *MockOrderRepositoryI {
	mock := &MockOrderRepositoryI{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepositoryI) EXPECT() *MockOrderRepositoryIMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOrderRepositoryI) Delete(id uint, hard bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, hard)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderRepositoryIMockRecorder) Delete(id, hard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderRepositoryI)(nil).Delete), id, hard)
}

// GetAll mocks base method.
func (m *MockOrderRepositoryI) GetAll() ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderRepositoryIMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderRepositoryI)(nil).GetAll))
}

// GetAllByUserId mocks base method.
func (m *MockOrderRepositoryI) GetAllByUserId(userId uint) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUserId", userId)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUserId indicates an expected call of GetAllByUserId.
func (mr *MockOrderRepositoryIMockRecorder) GetAllByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUserId", reflect.TypeOf((*MockOrderRepositoryI)(nil).GetAllByUserId), userId)
}

// GetById mocks base method.
func (m *MockOrderRepositoryI) GetById(id uint) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOrderRepositoryIMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOrderRepositoryI)(nil).GetById), id)
}

// Save mocks base method.
func (m *MockOrderRepositoryI) Save(order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOrderRepositoryIMockRecorder) Save(order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrderRepositoryI)(nil).Save), order)
}

// UpdateStatus mocks base method.
func (m *MockOrderRepositoryI) UpdateStatus(id uint, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOrderRepositoryIMockRecorder) UpdateStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOrderRepositoryI)(nil).UpdateStatus), id, status)
}
