// Code generated by MockGen. DO NOT EDIT.
// Source: ../services/user/user_service.go
//
// Generated by this command:
//
//	mockgen -source=../services/user/user_service.go -destination=mock_user_service_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	user "commerce/api/internal/dto/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceI is a mock of UserServiceI interface.
type MockUserServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceIMockRecorder
	isgomock struct{}
}

// MockUserServiceIMockRecorder is the mock recorder for MockUserServiceI.
type MockUserServiceIMockRecorder struct {
	mock *MockUserServiceI
}

// NewMockUserServiceI creates a new mock instance.
func NewMockUserServiceI(ctrl *gomock.Controller) *MockUserServiceI {
	mock := &MockUserServiceI{ctrl: ctrl}
	mock.recorder = &MockUserServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceI) EXPECT() *MockUserServiceIMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockUserServiceI) Authenticate(email, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", email, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockUserServiceIMockRecorder) Authenticate(email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockUserServiceI)(nil).Authenticate), email, password)
}

// Delete mocks base method.
func (m *MockUserServiceI) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserServiceIMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserServiceI)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockUserServiceI) GetAll() ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserServiceIMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserServiceI)(nil).GetAll))
}

// GetByEmail mocks base method.
func (m *MockUserServiceI) GetByEmail(email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserServiceIMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserServiceI)(nil).GetByEmail), email)
}

// GetById mocks base method.
func (m *MockUserServiceI) GetById(id uint) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserServiceIMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserServiceI)(nil).GetById), id)
}

// ResolveByAuth mocks base method.
func (m *MockUserServiceI) ResolveByAuth(sub, email, firstName, lastName string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveByAuth", sub, email, firstName, lastName)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveByAuth indicates an expected call of ResolveByAuth.
func (mr *MockUserServiceIMockRecorder) ResolveByAuth(sub, email, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveByAuth", reflect.TypeOf((*MockUserServiceI)(nil).ResolveByAuth), sub, email, firstName, lastName)
}

// Save mocks base method.
func (m *MockUserServiceI) Save(arg0 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserServiceIMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserServiceI)(nil).Save), arg0)
}
